sudo: false
language: csharp
solution: TravisExperiments.sln

matrix:
  include:
    #- dotnet: 2.1.4
    #  mono: none
    #  env: DOTNETCORE=1
    - mono: latest
      node_js: node

#install:

before_script:
  - |
    if [[ $DOTNETCORE = 1 ]]; then
      echo "dotnet core"
    else
      echo "mono"
    fi

script:
  - |
    if [[ $DOTNETCORE = 1 ]]; then
      dotnet build --framework netcoreapp2.0 TravisExperiments.sln
      dotnet bin/Debug/netcoreapp2.0/TravisExperiments.dll
    else
      msbuild /p:TargetFramework=net46 TravisExperiments.sln
      mono bin/Debug/net46/TravisExperiments.exe
    fi

#after_script:
#  - cd $MAIN_DIR
#  - chmod u+x ts3notify.sh
#  - ./ts3notify.sh
