sudo: false
language: c

cache:
  apt: true
  directories:
  - $HOME/cachebin

#install:

before_script:
  - export MAIN_DIR=`pwd`
  - cd $HOME
  - mkdir cachebin || (cd cachebin; touch testfile)

script:
  - cd $MAIN_DIR
  - cd ..

after_script:
  - cd $MAIN_DIR
  - chmod u+x ts3notify.sh
  - ./ts3notify.sh